### ISSUE TITLE
Excessive copying of queues to arrays in 2.2.14

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#107]
There's no need to copy queue contents to arrays before merging in 2.2.14 solution. Here's a simpler and faster method of queue merging:

```java
    public static Queue<Comparable> mergeQueues(Queue<Comparable> queue1, Queue<Comparable> queue2) {
        Queue<Comparable> mergedQueue = new Queue<>();
        
        while (!queue1.isEmpty() && !queue2.isEmpty()) {
            if(queue1.peek().compareTo(queue2.peek()) <= 0) {
                mergedQueue.enqueue(queue1.dequeue());
            } else {
                mergedQueue.enqueue(queue2.dequeue());
            }
        }
        
        while (!queue1.isEmpty()) {
            mergedQueue.enqueue(queue1.dequeue());
        }
        
        while (!queue2.isEmpty()) {
            mergedQueue.enqueue(queue2.dequeue());
        }
        
        return mergedQueue;
    }
```

**Comment by reneargento** [comment]
Looks like a trade-off between avoiding to use destructive operations on the queues and the extra space for the arrays + extra pass to copy the queue contents.
Since there is nothing in the question asking to avoid removing the items from the queues, your solution looks better. I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/067016f0cc94bc4403d99481e7c571b6bc35338a
Thanks!
