### ISSUE TITLE
1.3.47 Exercise says concatenation destructively using circular linkedlist but implemented differently. 

### ISSUE THREAD

**Issue by VBhojawala** [reneargento/algorithms-sedgewick-wayne#12]
Add an extra operation catenation that (destructively) concatenates two queues, stacks, or steques (see Exercise 1.3.32). Hint : Use circular linked list, maintaining a pointer to the last item.

**Comment by reneargento** [comment]
You are right, I updated the exercise to use circular linked lists: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/6357587fec8c9a3ae07949a3a9dbd759b792e879

**Comment by emergencyd** [comment]
Why does **StdOut.println("Expected: 0 1 2 3 7 8 9")** show in stack, queue, and steque. Since stack should be LIFO, I suppose the permutation might be reverse. 

Also, I am not sure whether the permutation of the steque should be the same with stack or queue.

**Comment by reneargento** [comment]
You are right, the stack catenation was incorrect. The steque catenation was correct, but since it only used the enqueue method to insert items, the permutation difference from the queue catenation was not clear.
I fixed the stack catenation and updated the way to insert items on the steque to make the permutation difference from the queue catenation clear.
The catenations are destructive because at the end of the operation both items that were passed as parameters are empty.
Exercise updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/a5207a30cc56773302c504004d8b53973c3b1b6d
Thanks!
