### ISSUE TITLE
(1.4.13) FixedCapacityStackOfStrings with capacity C and N entries

### ISSUE THREAD

**Issue by emergencyd** [reneargento/algorithms-sedgewick-wayne#127]
1) object overhead (16)
2) int (4)
3) padding (4)
4) String[C] with N entries
    String[C] is an array of objects. According to page 202, it is composed of 
    a) header (24)
    b) references (8C)
    c) String objects ((40 + 24 + 2N)*C)

    So I think the total memory should be
    16 + 4 + 4 + (24 + 8C + 64C + 2NC) = 48 + 72C + 2NC

    Actually I'm not sure what does "entries" mean. I use it as the number of chars in the String object. I'm not sure if the padding is right, either.

**Comment by reneargento** [comment]
I believe that entries refer to the number of strings, not characters.
So in this exercise we have a stack of fixed size C, with N strings in it, and we can consider that the strings have Ch chars.

So I believe that the correct computation would be:
```
1. object overhead (16)
2. int (4)
3. padding (4)
4. String[C] with N entries
a) header (24)
b) references (8C)
c) String objects ((40 + 24 + 2Ch)*N)

Total memory
16 + 4 + 4 + (24 + 8C + 64N + 2Ch*N) = 48 + 8C + 64N + 2Ch*N
```
While checking this I noted that I had not considered the values C and Ch in my computation so I updated the exercise: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/21e44f4c37a2ac2321f9c973516b03463bab4a4c

I used (56 + 2Ch) for the String object size instead of (64 + 2Ch) because newer editions of the book also have the description of Java 7+ strings, which have 8 bytes less than pre-java 7 strings.
