### ISSUE TITLE
2.3.9 I think answer to this exercise is no of time elements changes in array that many times partition mathod is called.

### ISSUE THREAD

**Issue by VBhojawala** [reneargento/algorithms-sedgewick-wayne#14]
I run code given at book site for following input and set the counter to partition method

String[] a = {"Q","S","T","Q","S","T","Q","S","T","T","Q","S","S","Q","Q","Q"};
String[] a = {"Q","S","Q","S","Q","S","Q","S","S","Q","Q","Q"};

so if you observe the count and order of input [no of time elements changes in supplied sequence] are matching.

**Comment by reneargento** [comment]
What do you mean by number of times elements change?
In the second example: {"Q","S","Q","S","Q","S","Q","S","S","Q","Q","Q"}, using a counter it seems that partition method is called 6 times and there are 9 element changes.

The initial order of elements should not matter much because the array is shuffled at the beginning of quicksort.

**Comment by reneargento** [comment]
Since the partition subroutine is called more than once for the two input arrays that you mentioned, the previous answer was not accurate. 
I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/1ebf5fcc5b79f8998aafdf92f593d90819164fec
