### ISSUE TITLE
2.5.2 Faster WordCombination 

### ISSUE THREAD

**Issue by VBhojawala** [reneargento/algorithms-sedgewick-wayne#15]
public class WordCombination {

	public static void getComPound(List<String> a) {
		int count = 0;
		Collections.sort(a);
		Set<String> wSet = new HashSet<>(a);

		for (int i = 0; i < a.size(); i++) {

			for (int j = i + 1; j < a.size(); j++) {
				if (!a.get(j).startsWith(a.get(i)))
					break;
				else {
					if (wSet.contains(a.get(j).substring(a.get(i).length()))) {
						System.out.println(a.get(i) + " + " + a.get(j).substring(a.get(i).length()) + " = " + a.get(j));
						count++;
					}
				}

			}
		}

		System.out.println("Total Count : " + count);
	}

	public static void main(String[] args) {

		List<String> a = new ArrayList<>();
		a.add("end");
		a.add("begin");
		a.add("start");
		a.add("startend");
		a.add("endstart");
		a.add("be");
		a.add("being");
		a.add("ing");
		a.add("bee");
		a.add("e");

		getComPound(a);
	}

}

**Comment by reneargento** [comment]
The problem with this approach is that the List.get() method has a complexity of O(n).
This is why I use a String[] array to iterate in the inner loop. This results in a method with runtime O(n^2).
Using a list it would have runtime O(n^3) due to the 2 loops and the List.get() calls inside the inner loop.

**Comment by VBhojawala** [comment]
I don't agree, list.get() takes O(1).

http://infotechgems.blogspot.in/2011/11/java-collections-performance-time.html

**Comment by reneargento** [comment]
You are right. I was thinking in the LinkedList implementation, that takes O(n) time to get an element.
The ArrayList class uses an array internally and takes O(1) time to get an element.

I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/802e89ef045911584fbcc5af9d9bc0c933a99f89
It is very similar to the code you posted but I force the parameter to be an ArrayList (instead of List) to guarantee the O(1) time to retrieve elements.

Thanks!

**Comment by reneargento** [comment]
I'm closing this issue as it has been fixed and the last comment was made over a year ago.
