### ISSUE TITLE
3.3.8 Can you justify your answer ?

### ISSUE THREAD

**Issue by VBhojawala** [reneargento/algorithms-sedgewick-wayne#16]

**Comment by reneargento** [comment]
A 4-node represented by three 2-nodes bounded together is basically 3 nodes connected.
The 6 ways represented in the answer are the 6 possible unique configurations. 

So in that case we consider 
A 
 B
  C

to be the same as 
B
 A
  C

because they have the same configuration, even though the nodes are in a different order.
I added a note to the exercise to mention this.

**Comment by reneargento** [comment]
I'm closing this issue as it has been addressed and the last comment was made over a year ago.
