### ISSUE TITLE
Exercise32_AVLTrees.java rotate* method implementation error

### ISSUE THREAD

**Issue by williamcheng-web** [reneargento/algorithms-sedgewick-wayne#162]
Thank you for your project, it helps me a lot.

I found an error in Exercise32_AVLTrees.java [rotateLeft](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/f31578352b7774e857a664bf8768bca2200e75e0/src/chapter3/section3/Exercise32_AVLTrees.java#L63).
>             newRoot.height = 1 + Math.max(height(newRoot.left), height(newRoot.right));
>             node.height = 1 + Math.max(height(node.left), height(node.right));
Above two lines should be interchanged. `newRoot` height should update after `node`.
Same error is also in [rotateRight](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/f31578352b7774e857a664bf8768bca2200e75e0/src/chapter3/section3/Exercise32_AVLTrees.java#L82).

It would be better to add height consistent check in `isAVL` method.

**Comment by reneargento** [comment]
I'm glad that the repository is being useful to you!

I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/f996f6d2e6fdc8c6a50f2610e8e962c5408793dc
The height consistency is checked on the `balanceFactor()` method used inside `isAVL()`. It didn't catch the issue in this case because on the examples tested the difference in height between the subtrees was never above 1.

Thanks for the contribution!
