### ISSUE TITLE
2.1.7

### ISSUE THREAD

**Issue by fuzhong-jiye** [reneargento/algorithms-sedgewick-wayne#194]
selection will only take N/2 exchanges, not N - 1

**Comment by vzhang** [comment]
good answer

**Comment by reneargento** [comment]
You are right, selection sort only makes N / 2 exchanges in that case.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/eec16ef30126d6365060c532fd6411b23b1c38c6
Thanks for the contribution!

**Comment by LudekCizinsky** [comment]
I understand your logic why selection would only take N/2 exchanges, but given the implementation in the book, number of exchanges for the selection sort will be O(n), no matter the input. Whereas, insertion will make O(n^2) and thus selection sort is for this particular case faster. (I have not mentioned number of comparisons since that is for both algorithms O(n^2)). Hope that makes sense..

**Comment by reneargento** [comment]
In this case, even with the book implementation, there will be only N / 2 exchanges.
Once we the external loop of the selection sort algorithm reaches the middle of the array, N / 2 exchanges will have been made and the array will already be sorted.
