### ISSUE TITLE
Exercise 34 Chapter 3 section2

### ISSUE THREAD

**Issue by Adeboye** [reneargento/algorithms-sedgewick-wayne#218]
Hello, I believe I found an error in the deleteMin and deleteMax methods in Chapter 3 section 2 Ex 34

on line 156 I believe  it should be 
`node.succ.pred = node.right`

and on line 178 it should be 
`node.prev.succ = node.left`

Updating the pred and succ to the new max and min values, apologies if I am wrong

Thanks again for this repo its awesome

**Comment by reneargento** [comment]
On the first case we are deleting the minimal node and on line 156 we are updating the minimal node's successor's pred.
With the minimal node deleted, its successor's `pred` should be null because its successor is now the new minimal node.
Similar logic applies to the deleteMax method with the `succ` field.
