### ISSUE TITLE
1.4.10, I found a non recursive version, may be helpful

### ISSUE THREAD

**Issue by ajfg93** [reneargento/algorithms-sedgewick-wayne#27]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/ac1dbf23355daebf37425eabcdd23bfea80bb94d/src/chapter1/section4/Exercise10.java#L32-L54

From SO: https://stackoverflow.com/questions/10148849/find-lowest-index-of-a-given-value-in-a-presorted-array

Your recursive version is indeed very cool! It took me some time to understand the magic. I found a non-recursive version on SO and it's neat and much staightforward. Maybe you could comment that in the original code as another source? 

Python code:

```
def binary_search(x, a):
    lo = 0
    hi = len(a)

    while lo < hi:
        mid = (lo + hi) // 2

        if a[mid] < x:
            lo = mid + 1
        elif a[mid] > x:
            hi = mid
        elif mid > 0 and a[mid-1] == x:
            hi = mid
        else:
            return mid

    return -1
```

Thank you for all the hard work btw, I am reading this book and visiting your repo frequently. :+1:

**Comment by reneargento** [comment]
Thanks for the suggestion!
I added it as an alternative solution here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/ef93b87326adec0b3ec5585e8cb5829b87ff13a7

I did a slight modification on the case when (array[middle] > element) because in this case the high variable can be set to middle - 1 instead of being set to middle.
