### ISSUE TITLE
ex 1.5.13 assign to the root of a heavier tree

### ISSUE THREAD

**Issue by kczapla** [reneargento/algorithms-sedgewick-wayne#291]
I think there is a room for improvement. `find` function finds roots and compress paths in the context of trees to be merged. At the time in code when they are invoked, they don't know which tree is going to be a new leader. So points on path from `p` to the root of tree `A` will be attached to the root of tree `A` and points on path form `q` to the root of tree `B` will be attached to the root of tree `B`.

If in the first place, new tree's root will be found and path compression is done against it, then all points on path originating from `p` and `q` will be attached to root of new tree.

What do you think?

**Comment by reneargento** [comment]
Consider a union of trees `A` and `B` that form tree `C`. Also consider that tree `A` is smaller than `B`.
With your idea we would have a tree that is more compressed, with all nodes having `C`’s root as parent. In the original approach we would have all nodes from `B` pointing to `C`’s root and the nodes from `A` pointing to `A`’s original root, which now points to `C`’s root. So we have one less level for `A`’s nodes, which is good.
On the other hand, to do that, we have to first find both roots (to know their sizes), the same way as the original approach, and then go through all the nodes on tree `A` again to update their pointers to `B`’s root (instead of just updating the parent of `A`’s root to `B`’s root).
So we end up with a more compressed tree but we also have to do extra operations (up to N / 2) to go over the smallest tree’s nodes again and update their parents.
Due to this trade-off I think your approach works better if we do a lot of searches / `find()` operations and less `union()` operations and the original approach works better for the opposite case.

**Comment by reneargento** [comment]
Actually, since the exercise mentions that the combination of weighted quick-union with path compression results in operations with an amortized cost bounded by the `inverse Ackermann function`, the resulting tree heights would always be small. So the original approach still seems to be the best option in all cases.

**Comment by Sdssourcing** [comment]
/

**Comment by Sdssourcing** [comment]
#
