### ISSUE TITLE
2.2.17 beforeLow usefulness

### ISSUE THREAD

**Issue by saraalaa** [reneargento/algorithms-sedgewick-wayne#301]
In 2.2.17 in mergesort function:
I want to know what the use of beforeLow here?
what happened if we don't use it at all?
Thank you

**Comment by reneargento** [comment]
`BeforeLow` is used to keep track of the first node before the two sub-lists being merged, so that the order is not lost.

You can see its usefulness in an example linked list with the values:
1 3 5 7 8 9 6 10

Assume that a merge will be done on two sublists of size 2 in the last 4 nodes: 8 9 and 6 10
In this case `beforeLow` points to the node with value 5.

After the merge is done we will have the last 4 nodes in the following order:
6 8 9 10

Then we can use `beforeLow` (node with value 5) to update its `next` pointer to node with value 6, keeping the order of the list.
