### ISSUE TITLE
4.4.11 -- Requesting Further Justification

### ISSUE THREAD

**Issue by LegendaryKokiri** [reneargento/algorithms-sedgewick-wayne#57]
Hello,

On Exercise 4.4.11, 16V bytes instead of 8V bytes are added for the Bag references in the adj[] array. This is corroborated by the booksite and is justified in your file as "resizing array," but best I can see, the array is never resized. Could you please explain this just a little bit more deeply?

Thank you,
LegendaryKokiri

**Comment by LegendaryKokiri** [comment]
Could it be that the default null references are being replaced by other references during initialization? Would we even count those?

**Comment by LegendaryKokiri** [comment]
Sorry, final note: The booksite implementation of EdgeWeightedDigraph has an extra int[] array that is not found in the implementation that they provide in the book. (Hence, it is not in your implementation either.) Could that be the discrepancy?

For convenience, here is a link to their implementation. (The extra array is private int[] indegree): https://algs4.cs.princeton.edu/44sp/EdgeWeightedDigraph.java.html

**Comment by reneargento** [comment]
Good point, the array is not resized, so we should only count 8V bytes for it.
After a closer look at the classes, it seems that the integer variable `size` in Bag class was not being counted.
It adds 4 bytes to the Bag class memory, which will then require 4 extra bytes of padding.
So this is a total of 8 extra bytes and since we have one Bag for each vertex, this is probably where the missing 8V bytes are coming from.

I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/fb6e40a7f3e36961cbdc64a1ba475b600c3b32c4

**Comment by LegendaryKokiri** [comment]
Oh, OK! Everything makes sense again! Thanks a million!
