### ISSUE TITLE
Question about 2.3.11

### ISSUE THREAD

**Issue by CharlieLei** [reneargento/algorithms-sedgewick-wayne#62]
I cannot understand the reason why the running time of quicksort becomes quadratic when the algorithm scans over items equal to the partitioning item? Would you please give a theoretical explanation or an example? Thank you very much!

**Comment by reneargento** [comment]
Consider the following array, with all equal elements:
`444444444444`

When the left index in the partition algorithm scans it, it will scan all elements because it continues moving when an element equal to the pivot is found.
The right index will also scan all elements on its left due to the same reason.
Because of this, the partition element returned will always be the first element of the array (you can debug exercise 2.3.11 using an array with all equal elements to verify this).
This will always partition the current array into 2 sub-arrays: one empty and another one with size equal to the previous subarray size - 1.
This process will repeat N times (as we reduce the size by 1 at each step). On the first step there are N comparisons (actually 2N, but we can simplify it as N), on the second step there are N - 1 comparisons, and so on, leading to the worst case of quick sort: O(N^2).
