### ISSUE TITLE
Question about 3.3.6 the probability of structural different 2-3 trees

### ISSUE THREAD

**Issue by Jungle1990** [reneargento/algorithms-sedgewick-wayne#64]
First of all, thanks very much for this repository to provide solutions of the algorithms book, it helps me a lot.
However, I'm confused about the your answer of question 3.3.6, it's relatively easy to work out 3.3.5 the different structural 2-3 trees with N nodes (for N=7, 8, 9, 10), but it's hard for me to figure out the probability.
Could you explain a bit more about it?

**Comment by reneargento** [comment]
I’m happy to know the repository has been useful to you!

After taking a look at this exercise, it seems that some cases of probabilities were missing, I updated them here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/cbbfee7bbf42b19b90ae82027cb11a257c01240e

Please check if they make more sense now.

To understand how they were calculated, take a look at the structure for trees with N = 6, shown in the book:
```
   ( )
() () ( )
```
From this structure, once we add a new key (and it becomes N = 7), there are 7 cases:

1- It may be added to the left of the first leaf node.
2- It may be added to the right of the first leaf node.
3- It may be added to the left of the second leaf node.
4- It may be added to the right of the second leaf node.
5- It may be added to the left of the third leaf node.
6- It may be added to the middle of the third leaf node.
7- It may be added to the right of the third leaf node.

Cases 1, 2, 3 and 4 lead to the following tree structure (ignore the order of the subtrees):
```
    ( )
 () ( ) ( )
```
Cases 5, 6 and 7 lead to the following tree structure:
```
     ()
  ()    ()
() () () ()
```
So the first structure has probability 4 / 7 and the second structure has probability 3 / 7.

For N = 8 it is a bit trickier because there are 2 possible structures for N = 7 (instead of only 1 with N = 6).

So we have to take into account the probability to get to that structure with N = 7 and then multiply it based on the different cases to get to N = 8 from that structure (as explained above for N = 7).

**Comment by Jungle1990** [comment]
Thanks very much! It makes sense now.
By the way, your idea that recursively gets the probability for N based on N-1 is very concise and clarifies the problem a lot. Initially, I was working on figuring out the relationship between the structure and node sequence (there are N! cases) to get all possible different structures for N, and quickly got stuck...
