### ISSUE TITLE
Simpler 3Sum

### ISSUE THREAD

**Issue by VBhojawala** [reneargento/algorithms-sedgewick-wayne#7]
private static int countThreeSum(int[] numbers) {
		int count=0;
		
		for(int i=0;i<numbers.length;i++) {
			int front=0,rear=numbers.length-1;
			
			while(front<rear) {
				if(numbers[front]+numbers[rear]+numbers[i]==0) {
					System.out.printf(String.format("Front : {%d}  Rear : {%d}  I : {%d}  \n", numbers[front],numbers[rear],numbers[i]));
					front++;rear--;
					count++;
				}else {
					if(Math.abs(numbers[front])>Math.abs(numbers[rear])) {
						front++;
					}else {
						rear--;
					}
				}
			}
		}
		
		
		return count;
	}

	public static void main(String[] args) {
		int[] numbers = { 1, 3, 5, 7, 12, 16, 19, 15, 11, 8, -1, -3, -7, -8, -11, -17, -15 };
		Arrays.sort(numbers);
		System.out.println(countThreeSum(numbers));
	}

**Comment by reneargento** [comment]
I believe there are a couple of problems with this approach:

1- numbers[front] and numbers[i] reference the same element in the first iteration, so the first element is evaluated twice. The array {-2, 5, 4} generates the result 
Front : {-2}  Rear : {4}  I : {-2} 
And the result set should be empty. 

2- Even if we fix this issue initializing front to i + 1  the {-10, -10, -5, 0, 5, 10, 10, 15, 20} array results in:

Front : {-10}  Rear : {20}  I : {-10}  
Front : {-5}  Rear : {15}  I : {-10}  
Front : {0}  Rear : {10}  I : {-10}  
Front : {-5}  Rear : {15}  I : {-10}  
Front : {0}  Rear : {10}  I : {-10}  
Front : {0}  Rear : {5}  I : {-5} 

But it is missing two more lines:
Front : {0}  Rear : {10}  I : {-10}  
Front : {0}  Rear : {10}  I : {-10}  

This is because there are two elements with value -10 and two elements with value 10 and one element with value 0 so we have four combinations of {-10, 0, 10}. The method in https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter1/section4/Exercise15_2_ThreeSumFaster.java takes care of this issue by checking all possible matches with the current element (at index i) and other elements at index start and end.
